services:
  - type: web
    name: stremio-moviebox
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: REQUEST_TIMEOUT
        value: 15
      - key: LOG_LEVEL
        value: INFO
      - key: PROXY_URL
        sync: false

